version: 2

jobs:
  build:
    docker:
    - image: lab259/go-circleci:1.12
    - image: redis:4.0.5-alpine

    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ .Branch }}-{{ checksum "go.sum" }}
            - deps-{{ .Branch }}-
            - deps-

      - run:
          name: Installing dependencies
          command: go mod download

      - run:
          name: Run tests
          command: make test

      - run:
          name: Coverage
          command: make coverage-ci

      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod

      - store_test_results:
          path: test-results

      - run: bash <(curl -s https://codecov.io/bash)